Add Front-End Functionality
taymoorKhalid/todolist pull request #1
Opened 2024-10-15 14:42 UTC by taymoorKhalid

React based frontEnd and Functionaity!

2024-10-18 06:42 UTC, DanyalNazir10 requested changes

2024-10-18 06:42 UTC, DanyalNazir10 commented on src/App.js
> +export default App;
Add EOF( End of file)

2024-10-18 06:42 UTC, DanyalNazir10 commented on src/components/todoItem/TodoItem.js
> +          <button className="item-left" onClick={toggleCompletion}>
Create common component for  buttons

2024-10-18 06:42 UTC, DanyalNazir10 commented on src/components/todoItem/TodoItem.js
> +            <p
No inline CSS.

2024-10-18 06:42 UTC, DanyalNazir10 commented on src/components/todoItem/TodoItem.js
> +                clip-rule="evenodd"
No inLine CSS

2024-10-18 06:42 UTC, DanyalNazir10 commented on src/components/todoList/TodoList.js
> +const TodoList = (props) => {
Instead of using "props." directly destruct the properties.

2024-10-18 13:36 UTC, taymoorKhalid commented
1) Changed Index.js to index.js.
2) Created a separate svg file.

2024-10-21 05:56 UTC, DanyalNazir10 approved these changes

2024-10-21 05:56 UTC, merged